### predict api

GET http://127.0.0.1:5000/predict HTTP/1.1
content-type: application/json

{
    "text":"white chocolate",
    "model":"bt",
    "threshold": "0.1"
}


### feedback to azure api

POST http://127.0.0.1:5000/postFeedback HTTP/1.1
Content-Type: "application/json"
x-access-token: mysecretkey

{
    "desc": "hazelnuts",
    "code": "A034L"
}

### authorise to private api
POST https://openapi.efsa.europa.eu/api/catalogues/catalogue-group-list HTTP/1.1
Content-Type: "application/json"
Ocp-Apim-Subscription-Key: mytoken

{     
   "getCatalogueGroupList": "" 
}

