### predict from specific model

GET http://127.0.0.1:5000/predict HTTP/1.1
content-type: application/json

{
    "text":"white chocolate",
    "model":"bt",
    "threshold": "0.1"
}
### predict from all models

GET http://127.0.0.1:5000/predictAll HTTP/1.1
content-type: application/json

{
    "text":"white chocolate",
    "threshold": "0.1"
}


### post feedback to azure table

POST http://127.0.0.1:5000/postFeedback HTTP/1.1
Content-Type: "application/json"
x-access-token: mysecretkey

{
    "desc": "hazelnuts",
    "code": "A034L"
}

